# Generated by Django 5.2.5 on 2025-08-31 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attempt',
            options={'permissions': [('can_view_all', 'Can view all items')], 'verbose_name': 'попытка', 'verbose_name_plural': 'попытки'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['full_name'], 'permissions': [('can_view_all', 'Can view all items')], 'verbose_name': 'клиент', 'verbose_name_plural': 'клиенты'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['topic'], 'permissions': [('can_view_all', 'Can view all items')], 'verbose_name': 'письмо', 'verbose_name_plural': 'письма'},
        ),
        migrations.AlterModelOptions(
            name='newsletter',
            options={'ordering': ['start_send_time'], 'permissions': [('can_view_all', 'Can view all items')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
    ]
