# Generated by Django 5.2.5 on 2025-09-01 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_alter_attempt_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'ordering': ['start_send_time'], 'permissions': [('can_view_all', 'Can view all items'), ('can_send_newsletters', 'Can send newsletters')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
        migrations.AddField(
            model_name='newsletter',
            name='name',
            field=models.CharField(default='Рассылка', help_text='Укажите название рассылки', max_length=100, verbose_name='Название'),
        ),
    ]
