# Generated by Django 5.2.5 on 2025-09-02 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0004_alter_newsletter_options_newsletter_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attempt',
            name='message',
        ),
        migrations.AddField(
            model_name='attempt',
            name='newsletter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='mail.newsletter', verbose_name='Рассылка'),
        ),
    ]
