# Generated by Django 5.2.5 on 2025-09-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0005_remove_attempt_message_attempt_newsletter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'ordering': ['start_send_time'], 'permissions': [('can_view_all', 'Can view all items'), ('can_send_newsletters', 'Can send newsletters'), ('can_manage', 'Can manage')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
        migrations.AddField(
            model_name='newsletter',
            name='is_blocked',
            field=models.BooleanField(default=False, verbose_name='Заблокирована?'),
        ),
    ]
